//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAADLPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component_Information
    {
        public int Component_Number { get; set; }
        public string Compnent_Name { get; set; }
        public Nullable<System.DateTime> Replacement_Date { get; set; }
        public Nullable<System.TimeSpan> Equipment_down_time { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Equipmment_Name { get; set; }
    }
}
