//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAADLPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Social_security { get; set; }
        public string Service_Date { get; set; }
        public string Description_ { get; set; }
        public string Skills_Required { get; set; }
    
        public virtual Maintenance_services Maintenance_services { get; set; }
    }
}
