//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAADLPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance_services
    {
        public int social_security { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Replacement_Date { get; set; }
        public Nullable<double> cost { get; set; }
        public string Shutdown_Maintenance { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
