//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAADLPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLogEvent
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    }
}
